alias ..='cd ..'
alias gb='cd ${OLDPWD}'
alias ccat='clear; cat'
alias ccd='clear; cd'
alias cl='clear'
alias clr='clear; cd ${HOME}'
alias clhr='clear; cd ${PWD}'
alias cla='clear; ls -A'
alias cls='clear; ls'
alias ctree='clear; tree'
alias cpwd='clear; pwd'
alias la='ls -A'
alias ls='ls --color=auto'
alias rf='rm -rf'
alias x='exit'
alias q='exit'
alias etc='cd "${PREFIX}/etc"'
